In [1]:
length = 5
width = 10
area = length * width
print(f"The length of rectange is: {length}")
print(f"The width of rectangle is: {width}")
print(f"The area of rectangle is: {area}")

The length of rectange is: 5
The width of rectangle is: 10
The area of rectangle is: 50


In [5]:
def func(a,b):
    if(a>b):
        print(f"{a} is greater than {b}")
    else:
        print(f"{b} is greater than {a}")

In [6]:
func(10,5)

10 is greater than 5


In [7]:
func(5,6)

6 is greater than 5


# Numpy array

In [10]:
# adding two lists of numbers
list1 = list(range(100))
list2 = list(range(100))
result_list = []

for i in range(len(list1)):
    result_list.append(list1[i] + list2[i])

print(result_list)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198]


In [14]:
# With NumPy arrays, the same operation is incredibly concise and fast
import numpy as np
arr1 = np.array(100)
arr2 = np.array(100)
result_lis = arr1+arr2
print(result_lis)

200


In [16]:
list = [1,2,3,4,5]    # 1-D array
ar1 = np.array(list)
print(ar1)
print(type(ar1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [17]:
list1 = [[1,2,3],[4,5,6],[7,8,9]]    # 2-D array
ar2 = np.array(list1)
print(ar2)
print(type(ar2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [19]:
# Creating 1-D array of 5 zeros
zeros_1d = np.zeros(5)
print(zeros_1d)

# Creating 2-D array of 2x4 zeros
zeros_2d = np.zeros((2,4))
print(zeros_2d)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [20]:
# Creating 1-D array of 5 ones
zeros_1d = np.ones(5)
print(zeros_1d)

# Creating 2-D array of 2x4 ones
zeros_2d = np.ones((2,4))
print(zeros_2d)

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Shape

The shape attribute returns a tuple indicating the size of the array in each dimension.

# Dtype

The dtype attribute tells you the data type of the elements stored in the array.

# Size

The size attribute returns the total number of elements in the array.

In [31]:
# Values from 0 to 9
range_arr1 = np.arange(10)
print(range_arr1)
print("1-D shape: ", range_arr1.shape)
print("1-D dtype: ", range_arr1.dtype)
print("1-D size: ", range_arr1.size)

# Values from 5 to 14
range_arr2 = np.arange(5, 15)
print(range_arr2)
print("1-D shape: ", range_arr2.shape)
print("1-D dtype: ", range_arr2.dtype)
print("1-D size: ", range_arr2.size)

# Values from 0 to 10 with a step of 2
range_arr3 = np.arange(0, 11, 2)
print(range_arr3)
print("1-D shape: ", range_arr3.shape)
print("1-D dtype: ", range_arr3.dtype)
print("1-D size: ", range_arr3.size)

# Values with floating-point step
range_arr4 = np.arange(0, 1, 0.2)
print(range_arr4)

# matrix shape
print("1-D shape: ", ar2.shape)
print("1-D dtype: ", ar2.dtype)
print("1-D size: ", ar2.size)

[0 1 2 3 4 5 6 7 8 9]
1-D shape:  (10,)
1-D dtype:  int64
1-D size:  10
[ 5  6  7  8  9 10 11 12 13 14]
1-D shape:  (10,)
1-D dtype:  int64
1-D size:  10
[ 0  2  4  6  8 10]
1-D shape:  (6,)
1-D dtype:  int64
1-D size:  6
[0.  0.2 0.4 0.6 0.8]
1-D shape:  (3, 3)
1-D dtype:  int64
1-D size:  9


# Accessing Elements and Slices

In [32]:
arr_1d = np.array([10, 20, 30, 40, 50])

# Get the first element (index 0)
first_element = arr_1d[0]
print(f"First element: {first_element}")

# Get the third element (index 2)
third_element = arr_1d[2]
print(f"Third element: {third_element}")

# Accessing the last element using negative indexing
last_element = arr_1d[-1]
print(f"Last element: {last_element}")

First element: 10
Third element: 30
Last element: 50


In [33]:
arr_1d = np.array([10, 20, 30, 40, 50, 60, 70])

# Elements from index 1 up to (but not including) index 4
slice1 = arr_1d[1:4]
print(f"Slice [1:4]: {slice1}")

# Elements from the beginning up to (not including) index 3
slice2 = arr_1d[:3]
print(f"Slice [:3]: {slice2}")

# Elements from index 3 to the end
slice3 = arr_1d[3:]
print(f"Slice [3:]: {slice3}")

# Every second element
slice4 = arr_1d[::2]
print(f"Slice [::2]: {slice4}")

# Elements from index 1 to 6 with a step of 2
slice5 = arr_1d[1:7:2]
print(f"Slice [1:7:2]: {slice5}")

# Reverse the array using slicing
reversed_arr = arr_1d[::-1]
print(f"Reversed array: {reversed_arr}")

Slice [1:4]: [20 30 40]
Slice [:3]: [10 20 30]
Slice [3:]: [40 50 60 70]
Slice [::2]: [10 30 50 70]
Slice [1:7:2]: [20 40 60]
Reversed array: [70 60 50 40 30 20 10]


In [34]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Get the element at the second row (index 1) and third column (index 2)
element_2d = arr_2d[1, 2]
print(f"Element at [1, 2]: {element_2d}")

# Equivalent using chained indexing (less common for multi-dim)
element_chained = arr_2d[1][2]
print(f"Element at [1][2] (chained): {element_chained}")

Element at [1, 2]: 6
Element at [1][2] (chained): 6


# Assigning data types

In [35]:
arr_int8 = np.array([10, -5, 127], dtype=np.int8)
print(f"int8 array: {arr_int8}, dtype: {arr_int8.dtype}")

# Attempting to store a value outside the range will cause overflow/wrap-around
# arr_overflow = np.array([130], dtype=np.int8) # This would wrap around to -126

arr_uint8 = np.array([10, 200, 255], dtype=np.uint8)
print(f"uint8 array: {arr_uint8}, dtype: {arr_uint8.dtype}")

int8 array: [ 10  -5 127], dtype: int8
uint8 array: [ 10 200 255], dtype: uint8


# Practical Application

In [48]:
# Student scores for Math, Science, English
scores_data = [
    [85, 92, 78],
    [90, 88, 82],
    [75, 80, 95],
    [92, 95, 88]
]
gpa_data = [3.5, 3.8, 3.2, 3.9]
scores = np.array(scores_data)
gpa = np.array(gpa_data)

# Get scores for Student 2
student_2_scores = scores[1,:]
print(f"Scores for Student 2: {student_2_scores}")

# Get the Science score for Student 4
print(scores[3,1])

# Get the GPA for Student 3
print(gpa[2])

# total students
print(scores.shape[0])   # return number of rows

# total subjects
print(scores.shape[1])  # return number of cols

# total score entris
print(scores.size)

Scores for Student 2: [90 88 82]
95
3.2
4
3
12


In [57]:
# Operations of 2 numpy arrays
a1 = np.array([10,12,24,35,16])
a2 = np.array([5,3,6,7,8])
print("Add: ", a1+a2)
print("Sub: ", a1-a2)
print("Multiply: ",a1*a2)
print("Divide: ", a1/a2)

# Calculating min, max, mean and standard deviation
print("Mean: ", a1.mean())
print("S.D.: ", a1.std())
print("Min: ",a1.min())
print("Max: ",a1.max())

# Broadcasting
# Adding Scaler to array
print("Broadcasting on 1-D array: ", a1+5)  # '5' will be added to all values stored in array 1

# Adding Scaler to 2-D array
a_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
vector_add = np.array([10,20,30])
print("Broadcasting on 2-D array: ", a_2d+vector_add)  # adding different values in row and cols

Add:  [15 15 30 42 24]
Sub:  [ 5  9 18 28  8]
Multiply:  [ 50  36 144 245 128]
Divide:  [2. 4. 4. 5. 2.]
Mean:  19.4
S.D.:  9.156418513807678
Min:  10
Max:  35
Broadcasting on 1-D array:  [15 17 29 40 21]
Broadcasting on 2-D array:  [[11 22 33]
 [14 25 36]
 [17 28 39]]


In [61]:
# Operation on Matrix
matrix_a = np.array([[1, 2],
                     [3, 4]])

matrix_b = np.array([[5, 6],
                     [7, 8]])

# --- Matrix Multiplication ---
print("Using @: ", matrix_a @ matrix_b)
print("Using np fucntion: ", np.dot(matrix_a, matrix_b))

# --- Transpose ---
print("Using .T: ", matrix_a.T)
print("Using np fucntion: ", np.transpose(matrix_a))

Using @:  [[19 22]
 [43 50]]
Using np fucntion:  [[19 22]
 [43 50]]
Using .T:  [[1 3]
 [2 4]]
Using np fucntion:  [[1 3]
 [2 4]]
